add user model
IT-Academy-Ruby/lessoner_project pull request #7
Opened 2022-08-21 18:37 UTC by Dmitryshl

2022-08-21 19:15 UTC, Terapool approved these changes

2022-08-22 06:57 UTC, fooooxmr requested changes

2022-08-22 06:57 UTC, fooooxmr commented on .idea/lessoner_project.iml
> +  </component>
You should not upload this folder to the git. Please setup .idea folder for gitignore and update your PR.

2022-08-22 06:57 UTC, fooooxmr commented on test/fixtures/users.yml
> +  about: MyString
We do not need this fixtures, since we are decided to use Rspec. Remove this file.

2022-08-22 06:57 UTC, fooooxmr commented on test/models/user_test.rb
> +end
Remove this file also and create _spec file instead.

2022-08-22 06:57 UTC, fooooxmr commented on app/models/user.rb
> +end
Please add validations.

2022-08-22 06:57 UTC, fooooxmr commented on db/migrate/20220821175150_create_users.rb
> +
Also add validations on the database level.

2022-08-22 06:58 UTC, fooooxmr commented on test/models/user_test.rb
> +end
https://github.com/rspec/rspec-rails/tree/6-0-maintenance

2022-08-22 06:59 UTC, fooooxmr commented on test/fixtures/users.yml
> +  about: MyString
We will use factory bot for this proposes https://github.com/thoughtbot/factory_bot

2022-08-23 06:19 UTC, fooooxmr requested changes

2022-08-23 06:19 UTC, fooooxmr commented on test/models/user.spec.rb
> +RSpec.describe User, type: :model do
Looks like you forgot to add end.

2022-08-23 06:19 UTC, fooooxmr commented on db/migrate/20220821175150_create_users.rb
> +      t.string :email
Please, make email uniq on the database level.
https://stackoverflow.com/questions/1449459/how-do-i-make-a-column-unique-and-index-it-in-a-ruby-on-rails-migration

2022-08-23 06:19 UTC, fooooxmr commented on .idea/lessoner_project.iml
> +  <component name="RakeTasksCache">
Remove this file from the commit. By some reason this file is still here.

2022-08-23 06:34 UTC, fooooxmr commented on .idea/lessoner_project.iml
> +  <component name="RakeTasksCache">
Also resolve merge conflicts.

2022-08-23 06:34 UTC, fooooxmr commented on .idea/lessoner_project.iml
> +  <component name="RakeTasksCache">
<img width="856" alt="image" src="https://user-images.githubusercontent.com/7360925/186087355-49674c2e-dc30-41f0-82ea-5398e06133bf.png">

2022-08-25 14:30 UTC, fooooxmr approved these changes

2022-08-25 14:30 UTC, Terapool approved these changes

2022-08-25 14:36 UTC, merged